# Generated by Django 4.2.11 on 2024-04-10 07:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guest_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(choices=[('Window View', 'Window View'), ('Cozy Corner', 'Cozy Corner'), ('Family Booth', 'Family Booth')], default='Window View', max_length=50, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
